<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Solución Taller 1: Preprocesamiento y Visualización de Datos</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="taller3_files/libs/clipboard/clipboard.min.js"></script>
<script src="taller3_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="taller3_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="taller3_files/libs/quarto-html/popper.min.js"></script>
<script src="taller3_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="taller3_files/libs/quarto-html/anchor.min.js"></script>
<link href="taller3_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="taller3_files/libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="taller3_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="taller3_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="taller3_files/libs/bootstrap/bootstrap-138a6193a3bd40baf1e627da441a4734.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
</head><body class="fullcontent quarto-light">\usepackage{longtable}
\usepackage[table]{xcolor}
\usepackage{array}
\usepackage{booktabs}






<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Solución Taller 1: Preprocesamiento y Visualización de Datos</h1>
<p class="subtitle lead">Universidad del Valle<br>
Facultad de Ingeniería<br>
Machine Learning para Gestión Financiera<br>
Profesor: Iván Mauricio Bermúdez Vera</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p> </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introducción" class="level2">
<h2 class="anchored" data-anchor-id="introducción"><strong>Introducción</strong></h2>
<p>El análisis del riesgo crediticio es una herramienta fundamental para las entidades financieras, ya que permite evaluar la capacidad de pago de los solicitantes y reducir la probabilidad de incumplimiento. En este trabajo se utiliza el conjunto de datos German Credit, compuesto por información financiera, laboral y sociodemográfica de 1.000 clientes, junto con una variable objetivo (default) que clasifica su comportamiento crediticio como bueno (good) o malo (bad).</p>
<p>Con el fin de preparar la información para futuras tareas de modelado predictivo, se realizó un proceso de diagnóstico y preprocesamiento de datos, seguido de un análisis exploratorio que permitió caracterizar las variables del conjunto de datos e identificar patrones relevantes asociados al comportamiento crediticio de los clientes.</p>
</section>
<section id="carga-del-conjunto-de-datos" class="level2">
<h2 class="anchored" data-anchor-id="carga-del-conjunto-de-datos">Carga del conjunto de datos</h2>
<p>El conjunto de datos German Credit presenta información sobre 1000 solicitantes de crédito. Cada variable en el conjunto permite una aproximación a las características financieras y socioeconómicas del potencial cliente a su vez que permite construir un análisis de estas variables con respecto a su comportamiento crediticio.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   V1 V2  V3  V4   V5  V6  V7 V8  V9  V10 V11  V12 V13  V14  V15 V16  V17 V18
1 A11  6 A34 A43 1169 A65 A75  4 A93 A101   4 A121  67 A143 A152   2 A173   1
2 A12 48 A32 A43 5951 A61 A73  2 A92 A101   2 A121  22 A143 A152   1 A173   1
3 A14 12 A34 A46 2096 A61 A74  2 A93 A101   3 A121  49 A143 A152   1 A172   2
4 A11 42 A32 A42 7882 A61 A74  2 A93 A103   4 A122  45 A143 A153   1 A173   2
5 A11 24 A33 A40 4870 A61 A73  3 A93 A101   4 A124  53 A143 A153   2 A173   2
6 A14 36 A32 A46 9055 A65 A73  2 A93 A101   4 A124  35 A143 A153   1 A172   2
   V19  V20 V21
1 A192 A201   1
2 A191 A201   2
3 A191 A201   1
4 A191 A201   1
5 A191 A201   2
6 A192 A201   1</code></pre>
</div>
</div>
<p>Como se logra evidenciar en la estructura anterior, hay registros que están codificados, además de que no se tienen el nombre de las columnas. En la siguiente sección, se realizará la limpieza y el preprocesamiento de los datos.</p>
</section>
<section id="diagnóstico-de-calidad-de-datos" class="level2">
<h2 class="anchored" data-anchor-id="diagnóstico-de-calidad-de-datos">Diagnóstico de calidad de datos</h2>
<p>Se asignaron nombres descriptivos a las 21 variables del conjunto de datos German Credit con el fin de facilitar su interpretación y análisis posterior.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Variable</th>
<th>Descripción</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>checking_status</td>
<td>Estado de la cuenta corriente</td>
</tr>
<tr class="even">
<td>duration</td>
<td>Duración del crédito (meses)</td>
</tr>
<tr class="odd">
<td>credit_history</td>
<td>Historial crediticio</td>
</tr>
<tr class="even">
<td>purpose</td>
<td>Propósito del crédito</td>
</tr>
<tr class="odd">
<td>credit_amount</td>
<td>Monto del crédito</td>
</tr>
<tr class="even">
<td>savings</td>
<td>Cuenta de ahorros / bonos</td>
</tr>
<tr class="odd">
<td>employment</td>
<td>Antigüedad laboral</td>
</tr>
<tr class="even">
<td>installment_rate</td>
<td>Tasa de cuota respecto al ingreso disponible</td>
</tr>
<tr class="odd">
<td>personal_status_sex</td>
<td>Estado civil y sexo</td>
</tr>
<tr class="even">
<td>other_debtors</td>
<td>Otros deudores o garantes</td>
</tr>
<tr class="odd">
<td>residence_since</td>
<td>Tiempo de residencia actual</td>
</tr>
<tr class="even">
<td>property</td>
<td>Tipo de propiedad</td>
</tr>
<tr class="odd">
<td>age</td>
<td>Edad</td>
</tr>
<tr class="even">
<td>other_installment_plans</td>
<td>Otros planes de pago</td>
</tr>
<tr class="odd">
<td>housing</td>
<td>Tipo de vivienda</td>
</tr>
<tr class="even">
<td>existing_credits</td>
<td>Número de créditos existentes en este banco</td>
</tr>
<tr class="odd">
<td>job</td>
<td>Ocupación</td>
</tr>
<tr class="even">
<td>people_liable</td>
<td>Número de personas a cargo</td>
</tr>
<tr class="odd">
<td>telephone</td>
<td>Disponibilidad de teléfono</td>
</tr>
<tr class="even">
<td>foreign_worker</td>
<td>Trabajador extranjero</td>
</tr>
<tr class="odd">
<td>default</td>
<td>Variable objetivo (Good / Bad)</td>
</tr>
</tbody>
</table>
<p>Se inicia verificando la estructura general de los datos, en los que se presentan 1000 observaciones y 20 variables. A continuación se presentan los tipos de variables donde se identifican 13 variables tipo caracter y 7 variables numéricas:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   1000 obs. of  21 variables:
 $ checking_status        : chr  "A11" "A12" "A14" "A11" ...
 $ duration               : int  6 48 12 42 24 36 24 36 12 30 ...
 $ credit_history         : chr  "A34" "A32" "A34" "A32" ...
 $ purpose                : chr  "A43" "A43" "A46" "A42" ...
 $ credit_amount          : int  1169 5951 2096 7882 4870 9055 2835 6948 3059 5234 ...
 $ savings                : chr  "A65" "A61" "A61" "A61" ...
 $ employment             : chr  "A75" "A73" "A74" "A74" ...
 $ installment_rate       : int  4 2 2 2 3 2 3 2 2 4 ...
 $ personal_status_sex    : chr  "A93" "A92" "A93" "A93" ...
 $ other_debtors          : chr  "A101" "A101" "A101" "A103" ...
 $ residence_since        : int  4 2 3 4 4 4 4 2 4 2 ...
 $ property               : chr  "A121" "A121" "A121" "A122" ...
 $ age                    : int  67 22 49 45 53 35 53 35 61 28 ...
 $ other_installment_plans: chr  "A143" "A143" "A143" "A143" ...
 $ housing                : chr  "A152" "A152" "A152" "A153" ...
 $ existing_credits       : int  2 1 1 1 2 1 1 1 1 2 ...
 $ job                    : chr  "A173" "A173" "A172" "A173" ...
 $ people_liable          : int  1 1 2 2 2 2 1 1 1 1 ...
 $ telephone              : chr  "A192" "A191" "A191" "A191" ...
 $ foreign_worker         : chr  "A201" "A201" "A201" "A201" ...
 $ default                : int  1 2 1 1 2 1 1 1 1 2 ...</code></pre>
</div>
</div>
<p>Se procede a convertir las variables categóricas a sus respectivas equivalencias denotadas en los atributos compartidos, a su vez que se convierte a formato factor:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Variable</th>
<th>Código original</th>
<th>Nueva categoría</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>checking_status</td>
<td>A11</td>
<td>less_0</td>
</tr>
<tr class="even">
<td>checking_status</td>
<td>A12</td>
<td>0_200</td>
</tr>
<tr class="odd">
<td>checking_status</td>
<td>A13</td>
<td>greater_200</td>
</tr>
<tr class="even">
<td>checking_status</td>
<td>A14</td>
<td>no_account</td>
</tr>
<tr class="odd">
<td>credit_history</td>
<td>A30</td>
<td>no_credit/all_paid</td>
</tr>
<tr class="even">
<td>credit_history</td>
<td>A31</td>
<td>all_paid</td>
</tr>
<tr class="odd">
<td>credit_history</td>
<td>A32</td>
<td>existing_paid</td>
</tr>
<tr class="even">
<td>credit_history</td>
<td>A33</td>
<td>delay</td>
</tr>
<tr class="odd">
<td>credit_history</td>
<td>A34</td>
<td>critical/other</td>
</tr>
<tr class="even">
<td>purpose</td>
<td>A40</td>
<td>car_new</td>
</tr>
<tr class="odd">
<td>purpose</td>
<td>A41</td>
<td>car_used</td>
</tr>
<tr class="even">
<td>purpose</td>
<td>A42</td>
<td>furniture/equipment</td>
</tr>
<tr class="odd">
<td>purpose</td>
<td>A43</td>
<td>radio/TV</td>
</tr>
<tr class="even">
<td>purpose</td>
<td>A44</td>
<td>domestic_appliances</td>
</tr>
<tr class="odd">
<td>purpose</td>
<td>A45</td>
<td>repairs</td>
</tr>
<tr class="even">
<td>purpose</td>
<td>A46</td>
<td>education</td>
</tr>
<tr class="odd">
<td>purpose</td>
<td>A47</td>
<td>vacation</td>
</tr>
<tr class="even">
<td>purpose</td>
<td>A48</td>
<td>retraining</td>
</tr>
<tr class="odd">
<td>purpose</td>
<td>A49</td>
<td>business</td>
</tr>
<tr class="even">
<td>purpose</td>
<td>A410</td>
<td>others</td>
</tr>
<tr class="odd">
<td>savings</td>
<td>A61</td>
<td>less_100</td>
</tr>
<tr class="even">
<td>savings</td>
<td>A62</td>
<td>100_500</td>
</tr>
<tr class="odd">
<td>savings</td>
<td>A63</td>
<td>500_1000</td>
</tr>
<tr class="even">
<td>savings</td>
<td>A64</td>
<td>greater_1000</td>
</tr>
<tr class="odd">
<td>savings</td>
<td>A65</td>
<td>unknown</td>
</tr>
<tr class="even">
<td>employment</td>
<td>A71</td>
<td>unemployed</td>
</tr>
<tr class="odd">
<td>employment</td>
<td>A72</td>
<td>less_1</td>
</tr>
<tr class="even">
<td>employment</td>
<td>A73</td>
<td>1_4</td>
</tr>
<tr class="odd">
<td>employment</td>
<td>A74</td>
<td>4_7</td>
</tr>
<tr class="even">
<td>employment</td>
<td>A75</td>
<td>greater_7</td>
</tr>
<tr class="odd">
<td>personal_status_sex</td>
<td>A91</td>
<td>male_divorced/separated</td>
</tr>
<tr class="even">
<td>personal_status_sex</td>
<td>A92</td>
<td>female_divorced/separated/married</td>
</tr>
<tr class="odd">
<td>personal_status_sex</td>
<td>A93</td>
<td>male_single</td>
</tr>
<tr class="even">
<td>personal_status_sex</td>
<td>A94</td>
<td>male_married</td>
</tr>
<tr class="odd">
<td>personal_status_sex</td>
<td>A95</td>
<td>female_single</td>
</tr>
<tr class="even">
<td>other_debtors</td>
<td>A101</td>
<td>none</td>
</tr>
<tr class="odd">
<td>other_debtors</td>
<td>A102</td>
<td>co_applicant</td>
</tr>
<tr class="even">
<td>other_debtors</td>
<td>A103</td>
<td>guarantor</td>
</tr>
<tr class="odd">
<td>property</td>
<td>A121</td>
<td>real_estate</td>
</tr>
<tr class="even">
<td>property</td>
<td>A122</td>
<td>building_society_savings_agreement/life_insurance</td>
</tr>
<tr class="odd">
<td>property</td>
<td>A123</td>
<td>car_or_other</td>
</tr>
<tr class="even">
<td>property</td>
<td>A124</td>
<td>unknown/no_property</td>
</tr>
<tr class="odd">
<td>other_installment_plans</td>
<td>A141</td>
<td>bank</td>
</tr>
<tr class="even">
<td>other_installment_plans</td>
<td>A142</td>
<td>stores</td>
</tr>
<tr class="odd">
<td>other_installment_plans</td>
<td>A143</td>
<td>none</td>
</tr>
<tr class="even">
<td>housing</td>
<td>A151</td>
<td>rent</td>
</tr>
<tr class="odd">
<td>housing</td>
<td>A152</td>
<td>own</td>
</tr>
<tr class="even">
<td>housing</td>
<td>A153</td>
<td>for_free</td>
</tr>
<tr class="odd">
<td>job</td>
<td>A171</td>
<td>unemployed/unskilled</td>
</tr>
<tr class="even">
<td>job</td>
<td>A172</td>
<td>unskilled_resident</td>
</tr>
<tr class="odd">
<td>job</td>
<td>A173</td>
<td>skilled/official</td>
</tr>
<tr class="even">
<td>job</td>
<td>A174</td>
<td>management/self-employed/highly_qualified</td>
</tr>
<tr class="odd">
<td>telephone</td>
<td>A191</td>
<td>none</td>
</tr>
<tr class="even">
<td>telephone</td>
<td>A192</td>
<td>yes</td>
</tr>
<tr class="odd">
<td>foreign_worker</td>
<td>A201</td>
<td>yes</td>
</tr>
<tr class="even">
<td>foreign_worker</td>
<td>A202</td>
<td>no</td>
</tr>
<tr class="odd">
<td>default</td>
<td>1</td>
<td>good</td>
</tr>
<tr class="even">
<td>default</td>
<td>2</td>
<td>bad</td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 1,000
Columns: 21
$ checking_status         &lt;fct&gt; less_0, 0_200, no_account, less_0, less_0, no_…
$ duration                &lt;int&gt; 6, 48, 12, 42, 24, 36, 24, 36, 12, 30, 12, 48,…
$ credit_history          &lt;fct&gt; critical_other, existing_paid, critical_other,…
$ purpose                 &lt;fct&gt; radio_tv, radio_tv, education, furniture_equip…
$ credit_amount           &lt;int&gt; 1169, 5951, 2096, 7882, 4870, 9055, 2835, 6948…
$ savings                 &lt;fct&gt; unknown, less_100, less_100, less_100, less_10…
$ employment              &lt;fct&gt; greater_7, 1_4, 4_7, 4_7, 1_4, 1_4, greater_7,…
$ installment_rate        &lt;int&gt; 4, 2, 2, 2, 3, 2, 3, 2, 2, 4, 3, 3, 1, 4, 2, 4…
$ personal_status_sex     &lt;fct&gt; male_single, female_divorced_separated_married…
$ other_debtors           &lt;fct&gt; none, none, none, guarantor, none, none, none,…
$ residence_since         &lt;int&gt; 4, 2, 3, 4, 4, 4, 4, 2, 4, 2, 1, 4, 1, 4, 4, 2…
$ property                &lt;fct&gt; real_estate, real_estate, real_estate, buildin…
$ age                     &lt;int&gt; 67, 22, 49, 45, 53, 35, 53, 35, 61, 28, 25, 24…
$ other_installment_plans &lt;fct&gt; none, none, none, none, none, none, none, none…
$ housing                 &lt;fct&gt; own, own, own, for_free, for_free, for_free, o…
$ existing_credits        &lt;int&gt; 2, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1…
$ job                     &lt;fct&gt; skilled_official, skilled_official, unskilled_…
$ people_liable           &lt;int&gt; 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
$ telephone               &lt;fct&gt; yes, none, none, none, none, yes, none, yes, n…
$ foreign_worker          &lt;fct&gt; yes, yes, yes, yes, yes, yes, yes, yes, yes, y…
$ default                 &lt;fct&gt; good, bad, good, good, bad, good, good, good, …</code></pre>
</div>
</div>
<p>Ahora, una vez realizada la recodificación, se realiza un resumen estadístico de las variables a analizar.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Resumen estadístico</caption>
<colgroup>
<col style="width: 0%">
<col style="width: 4%">
<col style="width: 3%">
<col style="width: 6%">
<col style="width: 5%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 9%">
<col style="width: 4%">
<col style="width: 3%">
<col style="width: 10%">
<col style="width: 3%">
<col style="width: 5%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 10%">
<col style="width: 3%">
<col style="width: 2%">
<col style="width: 3%">
<col style="width: 2%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">checking_status</th>
<th style="text-align: left;">duration</th>
<th style="text-align: left;">credit_history</th>
<th style="text-align: left;">purpose</th>
<th style="text-align: left;">credit_amount</th>
<th style="text-align: left;">savings</th>
<th style="text-align: left;">employment</th>
<th style="text-align: left;">installment_rate</th>
<th style="text-align: left;">personal_status_sex</th>
<th style="text-align: left;">other_debtors</th>
<th style="text-align: left;">residence_since</th>
<th style="text-align: left;">property</th>
<th style="text-align: left;">age</th>
<th style="text-align: left;">other_installment_plans</th>
<th style="text-align: left;">housing</th>
<th style="text-align: left;">existing_credits</th>
<th style="text-align: left;">job</th>
<th style="text-align: left;">people_liable</th>
<th style="text-align: left;">telephone</th>
<th style="text-align: left;">foreign_worker</th>
<th style="text-align: left;">default</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">0_200 :269</td>
<td style="text-align: left;">Min. : 4.0</td>
<td style="text-align: left;">all_paid : 49</td>
<td style="text-align: left;">radio_tv :280</td>
<td style="text-align: left;">Min. : 250</td>
<td style="text-align: left;">100_500 :103</td>
<td style="text-align: left;">1_4 :339</td>
<td style="text-align: left;">Min. :1.000</td>
<td style="text-align: left;">female_divorced_separated_married:310</td>
<td style="text-align: left;">co_applicant: 41</td>
<td style="text-align: left;">Min. :1.000</td>
<td style="text-align: left;">building_society_savings_life_insurance:232</td>
<td style="text-align: left;">Min. :19.00</td>
<td style="text-align: left;">bank :139</td>
<td style="text-align: left;">for_free:108</td>
<td style="text-align: left;">Min. :1.000</td>
<td style="text-align: left;">management_self_employed_highly_qualified:148</td>
<td style="text-align: left;">Min. :1.000</td>
<td style="text-align: left;">none:596</td>
<td style="text-align: left;">no : 37</td>
<td style="text-align: left;">bad :300</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">greater_200: 63</td>
<td style="text-align: left;">1st Qu.:12.0</td>
<td style="text-align: left;">critical_other :293</td>
<td style="text-align: left;">car_new :234</td>
<td style="text-align: left;">1st Qu.: 1366</td>
<td style="text-align: left;">500_1000 : 63</td>
<td style="text-align: left;">4_7 :174</td>
<td style="text-align: left;">1st Qu.:2.000</td>
<td style="text-align: left;">male_divorced_separated : 50</td>
<td style="text-align: left;">guarantor : 52</td>
<td style="text-align: left;">1st Qu.:2.000</td>
<td style="text-align: left;">car_or_other :332</td>
<td style="text-align: left;">1st Qu.:27.00</td>
<td style="text-align: left;">none :814</td>
<td style="text-align: left;">own :713</td>
<td style="text-align: left;">1st Qu.:1.000</td>
<td style="text-align: left;">skilled_official :630</td>
<td style="text-align: left;">1st Qu.:1.000</td>
<td style="text-align: left;">yes :404</td>
<td style="text-align: left;">yes:963</td>
<td style="text-align: left;">good:700</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">less_0 :274</td>
<td style="text-align: left;">Median :18.0</td>
<td style="text-align: left;">delay : 88</td>
<td style="text-align: left;">furniture_equipment:181</td>
<td style="text-align: left;">Median : 2320</td>
<td style="text-align: left;">greater_1000: 48</td>
<td style="text-align: left;">greater_7 :253</td>
<td style="text-align: left;">Median :3.000</td>
<td style="text-align: left;">male_married : 92</td>
<td style="text-align: left;">none :907</td>
<td style="text-align: left;">Median :3.000</td>
<td style="text-align: left;">real_estate :282</td>
<td style="text-align: left;">Median :33.00</td>
<td style="text-align: left;">stores: 47</td>
<td style="text-align: left;">rent :179</td>
<td style="text-align: left;">Median :1.000</td>
<td style="text-align: left;">unemployed_unskilled : 22</td>
<td style="text-align: left;">Median :1.000</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">no_account :394</td>
<td style="text-align: left;">Mean :20.9</td>
<td style="text-align: left;">existing_paid :530</td>
<td style="text-align: left;">car_used :103</td>
<td style="text-align: left;">Mean : 3271</td>
<td style="text-align: left;">less_100 :603</td>
<td style="text-align: left;">less_1 :172</td>
<td style="text-align: left;">Mean :2.973</td>
<td style="text-align: left;">male_single :548</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Mean :2.845</td>
<td style="text-align: left;">unknown_no_property :154</td>
<td style="text-align: left;">Mean :35.55</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Mean :1.407</td>
<td style="text-align: left;">unskilled_resident :200</td>
<td style="text-align: left;">Mean :1.155</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">3rd Qu.:24.0</td>
<td style="text-align: left;">no_credit_all_paid: 40</td>
<td style="text-align: left;">business : 97</td>
<td style="text-align: left;">3rd Qu.: 3972</td>
<td style="text-align: left;">unknown :183</td>
<td style="text-align: left;">unemployed: 62</td>
<td style="text-align: left;">3rd Qu.:4.000</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">3rd Qu.:4.000</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">3rd Qu.:42.00</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">3rd Qu.:2.000</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">3rd Qu.:1.000</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Max. :72.0</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">education : 50</td>
<td style="text-align: left;">Max. :18424</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Max. :4.000</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Max. :4.000</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Max. :75.00</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Max. :4.000</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Max. :2.000</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">(Other) : 55</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
</tbody>
</table>
</div>
</div>
<section id="resumen-estadístico-de-las-variables" class="level3">
<h3 class="anchored" data-anchor-id="resumen-estadístico-de-las-variables">Resumen estadístico de las variables</h3>
<p>El conjunto de datos <em>German Credit</em> está conformado por 1.000 registros y 21 variables, de las cuales 7 son numéricas y 14 categóricas. El análisis descriptivo inicial permite identificar características relevantes de la población estudiada y posibles patrones asociados al riesgo crediticio.</p>
<section id="variables-numéricas" class="level4">
<h4 class="anchored" data-anchor-id="variables-numéricas">Variables numéricas</h4>
<p>La duración de los créditos (<code>duration</code>) presenta una mediana de 18 meses y una media de 20,9 meses, lo que indica que la mayoría de los préstamos corresponden a compromisos financieros de corto y mediano plazo. Sin embargo, se observan créditos con duraciones de hasta 72 meses, evidenciando una dispersión considerable en esta variable.</p>
<p>El monto del crédito (<code>credit_amount</code>) registra una media de 3.271 unidades monetarias y una mediana de 2.320. La diferencia entre ambas medidas sugiere una distribución asimétrica hacia la derecha, ocasionada por la presencia de créditos de alto valor que alcanzan montos de hasta 18.424 unidades monetarias.</p>
<p>La edad de los solicitantes (<code>age</code>) oscila entre 19 y 75 años, con una media de 35,5 años y una mediana de 33 años. Esto indica que la mayor parte de los clientes corresponde a población económicamente activa en etapas tempranas y medias de su vida laboral.</p>
<p>Las variables <code>installment_rate</code>, <code>residence_since</code>, <code>existing_credits</code> y <code>people_liable</code> presentan rangos relativamente reducidos, reflejando estructuras de información discretas y con baja variabilidad. En particular, la mayoría de los clientes posee un solo crédito activo en el banco y una sola persona dependiente económicamente.</p>
</section>
<section id="variables-categóricas" class="level4">
<h4 class="anchored" data-anchor-id="variables-categóricas">Variables categóricas</h4>
<p>Respecto al estado de la cuenta corriente (<code>checking_status</code>), la categoría más frecuente corresponde a clientes sin cuenta corriente (<code>no_account</code>), representando aproximadamente el 39 % de los registros. Esto indica que una proporción importante de solicitantes no posee este producto financiero.</p>
<p>En el historial crediticio (<code>credit_history</code>), más de la mitad de los clientes (53 %) se ubica en la categoría <code>existing_paid</code>, correspondiente a créditos que han sido pagados correctamente hasta el momento. Adicionalmente, un 29,3 % pertenece a la categoría <code>critical_other</code>, lo que sugiere antecedentes financieros más complejos.</p>
<p>En cuanto al propósito del crédito (<code>purpose</code>), predominan las solicitudes para adquisición de radio o televisión (28 %), vehículos nuevos (23,4 %) y muebles o equipamiento del hogar (18,1 %). Estas tres categorías concentran cerca del 70 % de los créditos otorgados.</p>
<p>La variable de ahorro (<code>savings</code>) muestra que el 60,3 % de los clientes posee menos de 100 unidades monetarias ahorradas, mientras que únicamente el 4,8 % reporta ahorros superiores a 1.000 unidades. Esto evidencia una capacidad de ahorro limitada para una gran proporción de los solicitantes.</p>
<p>En términos laborales (<code>employment</code>), la categoría más frecuente corresponde a personas con entre 1 y 4 años de antigüedad laboral (33,9 %), seguida por quienes tienen más de 7 años de experiencia laboral (25,3 %). Esto sugiere una población con relativa estabilidad laboral.</p>
<p>Respecto a la vivienda (<code>housing</code>), el 71,3 % de los clientes reside en vivienda propia, mientras que el 17,9 % vive en arriendo. Este resultado puede interpretarse como un indicador indirecto de estabilidad económica.</p>
<p>La ocupación (<code>job</code>) muestra una clara predominancia de trabajadores calificados u oficiales (<code>skilled_official</code>), quienes representan el 63 % de la muestra. Por el contrario, las categorías asociadas a desempleo o baja cualificación presentan una participación reducida.</p>
<p>Finalmente, la variable objetivo (<code>default</code>) evidencia un desbalance entre clases: el 70 % de los clientes presenta un comportamiento crediticio bueno (<code>good</code>), mientras que el 30 % corresponde a clientes con comportamiento malo (<code>bad</code>). Este aspecto será importante en etapas posteriores de modelado predictivo, ya que podría influir en el desempeño de los algoritmos de clasificación.</p>
</section>
<section id="hallazgos-relevantes" class="level4">
<h4 class="anchored" data-anchor-id="hallazgos-relevantes">Hallazgos relevantes</h4>
<p>Los resultados muestran una población caracterizada principalmente por clientes con historial crediticio favorable, estabilidad laboral moderada, vivienda propia y montos de crédito relativamente bajos o medios. Sin embargo, se observa una importante concentración de solicitantes con bajos niveles de ahorro y una distribución asimétrica en el monto de los créditos, lo que sugiere la posible existencia de valores extremos. Asimismo, el desbalance de la variable objetivo constituye un aspecto relevante a considerar en futuros modelos de clasificación de riesgo crediticio.</p>
<p>Posteriormente se definieron reglas de validación utilizando el paquete <code>validate</code> con el objetivo de verificar la consistencia lógica de las variables numéricas y categóricas del conjunto de datos.</p>
<p>Para las variables numéricas se comprobó que atributos como la duración del crédito, monto del préstamo, edad del solicitante y número de créditos existentes presentaran valores positivos o no negativos según correspondiera. De igual forma, para las variables categóricas se verificó que cada observación perteneciera exclusivamente al conjunto de categorías válidas definidas durante el proceso de recodificación.</p>
<p>Estas validaciones permitieron asegurar que los registros cumplen con las restricciones establecidas por la naturaleza de cada variable y que no existen valores fuera de rango o categorías inválidas que puedan afectar el análisis posterior.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Object of class 'validator' with 21 elements:
 V01: german[["duration"]] &gt; 0
 V02: german[["credit_amount"]] &gt; 0
 V03: german[["installment_rate"]] &gt; 0
 V04: german[["residence_since"]] &gt; 0
 V05: german[["age"]] &gt; 0
 V06: german[["existing_credits"]] &gt;= 0
 V07: german[["people_liable"]] &gt;= 0
 V08: checking_status %in% unname(dict_mapping[["checking_status"]])
 V09: credit_history %in% unname(dict_mapping[["credit_history"]])
 V10: purpose %in% unname(dict_mapping[["purpose"]])
 V11: savings %in% unname(dict_mapping[["savings"]])
 V12: employment %in% unname(dict_mapping[["employment"]])
 V13: personal_status_sex %in% unname(dict_mapping[["personal_status_sex"]])
 V14: other_debtors %in% unname(dict_mapping[["other_debtors"]])
 V15: property %in% unname(dict_mapping[["property"]])
 V16: other_installment_plans %in% unname(dict_mapping[["other_installment_plans"]])
 V17: housing %in% unname(dict_mapping[["housing"]])
 V18: job %in% unname(dict_mapping[["job"]])
 V19: telephone %in% unname(dict_mapping[["telephone"]])
 V20: foreign_worker %in% unname(dict_mapping[["foreign_worker"]])
 V21: default %in% unname(dict_mapping[["default"]])</code></pre>
</div>
</div>
<p>Se definen cuántas filas presentan al menos una regla incumplida y se encuentra que el número es cero.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>integer(0)</code></pre>
</div>
</div>
<p>A su vez, se encuentra que el número de datos faltantes en toda la base es igualmente cero.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(german))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="taller3_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="detección-de-valores-atípicos-mediante-el-criterio-de-tukey" class="level3">
<h3 class="anchored" data-anchor-id="detección-de-valores-atípicos-mediante-el-criterio-de-tukey">Detección de valores atípicos mediante el criterio de Tukey</h3>
<p>Una vez se revisan los datos faltantes, se procede a realizar un análisis de anomalías. Para ello, se usa el <em>criterio Tukey</em>:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Detección de valores atípicos mediante el criterio de Tukey</caption>
<colgroup>
<col style="width: 18%">
<col style="width: 7%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 9%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: right;">Q1</th>
<th style="text-align: right;">Q3</th>
<th style="text-align: right;">IQR</th>
<th style="text-align: right;">Limite_Inferior</th>
<th style="text-align: right;">Limite_Superior</th>
<th style="text-align: right;">Atipicos</th>
<th style="text-align: right;">Porcentaje</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">duration</td>
<td style="text-align: right;">12.0</td>
<td style="text-align: right;">24.00</td>
<td style="text-align: right;">12.00</td>
<td style="text-align: right;">-6.00</td>
<td style="text-align: right;">42.00</td>
<td style="text-align: right;">70</td>
<td style="text-align: right;">7.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">credit_amount</td>
<td style="text-align: right;">1365.5</td>
<td style="text-align: right;">3972.25</td>
<td style="text-align: right;">2606.75</td>
<td style="text-align: right;">-2544.62</td>
<td style="text-align: right;">7882.38</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">7.2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">installment_rate</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: right;">4.00</td>
<td style="text-align: right;">2.00</td>
<td style="text-align: right;">-1.00</td>
<td style="text-align: right;">7.00</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">residence_since</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: right;">4.00</td>
<td style="text-align: right;">2.00</td>
<td style="text-align: right;">-1.00</td>
<td style="text-align: right;">7.00</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">age</td>
<td style="text-align: right;">27.0</td>
<td style="text-align: right;">42.00</td>
<td style="text-align: right;">15.00</td>
<td style="text-align: right;">4.50</td>
<td style="text-align: right;">64.50</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">2.3</td>
</tr>
<tr class="even">
<td style="text-align: left;">existing_credits</td>
<td style="text-align: right;">1.0</td>
<td style="text-align: right;">2.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">-0.50</td>
<td style="text-align: right;">3.50</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0.6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">people_liable</td>
<td style="text-align: right;">1.0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">155</td>
<td style="text-align: right;">15.5</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="taller3_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 326 × 3
   Variable  Fila Valor
   &lt;chr&gt;    &lt;int&gt; &lt;int&gt;
 1 duration     2    48
 2 duration    12    48
 3 duration    30    60
 4 duration    36    45
 5 duration    37    48
 6 duration    45    48
 7 duration    64    48
 8 duration    79    54
 9 duration    96    54
10 duration   116    48
# ℹ 316 more rows</code></pre>
</div>
</div>
<p>Con base en el <em>criterio Tukey</em>, los resultados evidencian la presencia de valores atípicos en algunas variables del conjunto de datos. Las variables <code>duration</code> y <code>credit_amount</code> presentan 70 y 72 observaciones atípicas respectivamente, correspondientes al 7,0 % y 7,2 % de la muestra. Estos resultados sugieren la existencia de créditos con duraciones o montos significativamente superiores al comportamiento habitual de la población analizada.</p>
<p>La variable <code>age</code> presenta 23 observaciones atípicas (2,3 %), asociadas principalmente a solicitantes de mayor edad. Sin embargo, dado que los valores observados se encuentran dentro de rangos plausibles para la población económicamente activa, no se consideran errores de registro.</p>
<p>Por su parte, la variable <code>existing_credits</code> presenta únicamente 6 observaciones atípicas (0,6 %), lo que indica una baja presencia de clientes con un número inusualmente alto de créditos vigentes en la entidad financiera.</p>
<p>La variable <code>people_liable</code> registra 155 observaciones atípicas (15,5 %), siendo la proporción más alta entre todas las variables analizadas. No obstante, este resultado debe interpretarse con cautela, ya que la variable es discreta y presenta una distribución altamente concentrada en el valor 1. Debido a que el rango intercuartílico (IQR) es igual a cero, cualquier observación diferente a dicho valor es identificada automáticamente como atípica por el criterio de Tukey. Por esta razón, estos registros no necesariamente representan anomalías reales.</p>
<p>Las variables <code>installment_rate</code> y <code>residence_since</code> no presentan valores atípicos según el criterio aplicado, lo que indica una distribución relativamente homogénea dentro de los rangos esperados.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="taller3_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="taller3_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="1152"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">n_out_mahalanobis</th>
<th style="text-align: right;">n_out_lof</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">35</td>
<td style="text-align: right;">10</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Con el propósito de complementar la detección univariada de valores atípicos, se realizó un análisis multivariado sobre las variables numéricas del conjunto de datos. Inicialmente, la matriz de dispersión permitió examinar las relaciones existentes entre las variables y calcular los coeficientes de correlación de Pearson.</p>
<p>Los resultados evidencian que la relación más importante se presenta entre la duración del crédito (<em>duration</em>) y el monto solicitado (<em>credit_amount</em>), con una correlación positiva moderada (r = 0.625), lo que indica que los créditos de mayor valor suelen asociarse con plazos de pago más extensos. Asimismo, se observan correlaciones positivas de menor magnitud entre la edad (<em>age</em>) y el tiempo de residencia (<em>residence_since</em>), así como entre la edad y el número de créditos existentes (<em>existing_credits</em>). En general, la mayoría de las variables presentan correlaciones débiles, lo que sugiere una baja dependencia lineal entre ellas.</p>
<p>Posteriormente, se aplicaron dos técnicas de detección de anomalías multivariadas: la Distancia de Mahalanobis y el algoritmo Local Outlier Factor (LOF). La primera identificó 35 observaciones con patrones significativamente alejados del comportamiento promedio de la población, mientras que el método LOF detectó 10 observaciones con características inusuales respecto a sus vecinos más cercanos.</p>
<p>Si bien se identificaron registros potencialmente atípicos, estos corresponden a observaciones válidas dentro del contexto del negocio y no a errores de captura o inconsistencias en los datos. Por esta razón, se decidió conservarlos para las etapas posteriores del análisis, considerando que los perfiles extremos pueden aportar información relevante para la comprensión del riesgo crediticio y la construcción de futuros modelos de clasificación.</p>
</section>
</section>
<section id="análisis-exploratorio" class="level2">
<h2 class="anchored" data-anchor-id="análisis-exploratorio">Análisis exploratorio</h2>
<section id="distribución-de-la-variable-objetivo-default" class="level3">
<h3 class="anchored" data-anchor-id="distribución-de-la-variable-objetivo-default">Distribución de la variable objetivo (default)</h3>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="taller3_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>La variable objetivo (<em>default</em>) presenta una distribución desbalanceada, donde el 70,0% de los registros corresponde a clientes clasificados con buen comportamiento crediticio (<em>good</em>) y el 30,0% restante a clientes con comportamiento desfavorable (<em>bad</em>). Esta diferencia deberá considerarse en etapas posteriores de modelado, ya que podría influir en el desempeño de los algoritmos de clasificación.</p>
</section>
<section id="análisis-descriptivo-de-variables-cuantitativas" class="level3">
<h3 class="anchored" data-anchor-id="análisis-descriptivo-de-variables-cuantitativas">Análisis descriptivo de variables cuantitativas</h3>
<p>Se presenta inicialmente los estadísticos descriptivos de las variables numéricas:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Estadísticos descriptivos de las variables numéricas</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Media</th>
<th style="text-align: right;">Mediana</th>
<th style="text-align: right;">Desv_Est</th>
<th style="text-align: right;">Minimo</th>
<th style="text-align: right;">Maximo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">duration</td>
<td style="text-align: right;">20.90</td>
<td style="text-align: right;">18.0</td>
<td style="text-align: right;">12.06</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">72</td>
</tr>
<tr class="even">
<td style="text-align: left;">credit_amount</td>
<td style="text-align: right;">3271.26</td>
<td style="text-align: right;">2319.5</td>
<td style="text-align: right;">2822.74</td>
<td style="text-align: right;">250</td>
<td style="text-align: right;">18424</td>
</tr>
<tr class="odd">
<td style="text-align: left;">installment_rate</td>
<td style="text-align: right;">2.97</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: right;">1.12</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="even">
<td style="text-align: left;">residence_since</td>
<td style="text-align: right;">2.85</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: right;">1.10</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">age</td>
<td style="text-align: right;">35.55</td>
<td style="text-align: right;">33.0</td>
<td style="text-align: right;">11.38</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">75</td>
</tr>
<tr class="even">
<td style="text-align: left;">existing_credits</td>
<td style="text-align: right;">1.41</td>
<td style="text-align: right;">1.0</td>
<td style="text-align: right;">0.58</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">people_liable</td>
<td style="text-align: right;">1.16</td>
<td style="text-align: right;">1.0</td>
<td style="text-align: right;">0.36</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="taller3_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Los estadísticos descriptivos permiten identificar una marcada heterogeneidad en las características financieras de los solicitantes. La duración de los créditos presenta una media de 20,9 meses y una mediana de 18 meses, lo que indica una ligera asimetría hacia créditos de mayor plazo. De manera similar, el monto del crédito exhibe una elevada dispersión (desviación estándar de 2.822,74 DM) y una diferencia considerable entre la media (3.271,26 DM) y la mediana (2.319,5 DM), sugiriendo la presencia de algunos créditos de valor significativamente superior al promedio. Esta característica también se evidencia en el gráfico de densidad, donde se observa una concentración importante de créditos de bajo monto y una cola alargada hacia valores altos.</p>
<p>La edad de los solicitantes presenta una media de 35,55 años y una mediana de 33 años, lo que indica que la población analizada está compuesta principalmente por adultos jóvenes y de mediana edad. Por su parte, variables como la tasa de cuota (<em>installment_rate</em>), el tiempo de residencia (<em>residence_since</em>), el número de créditos existentes (<em>existing_credits</em>) y el número de personas a cargo (<em>people_liable</em>) muestran una variabilidad reducida debido a que sus valores se encuentran acotados dentro de un rango limitado. En particular, la variable <em>people_liable</em> se concentra casi exclusivamente en un solo dependiente, mientras que la mayoría de los clientes posee uno o dos créditos activos en la entidad financiera. En conjunto, los resultados evidencian distribuciones asimétricas en variables relacionadas con el nivel de endeudamiento, aspecto que deberá considerarse en las etapas posteriores del análisis y modelado.</p>
</section>
<section id="análisis-descriptivo-de-variables-categóricas" class="level3">
<h3 class="anchored" data-anchor-id="análisis-descriptivo-de-variables-categóricas">Análisis descriptivo de variables categóricas</h3>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Resumen descriptivo de variables categóricas</caption>
<colgroup>
<col style="width: 35%">
<col style="width: 16%">
<col style="width: 25%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: right;">Categorias</th>
<th style="text-align: left;">Moda</th>
<th style="text-align: right;">Frecuencia_moda</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">checking_status</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">no_account</td>
<td style="text-align: right;">394</td>
</tr>
<tr class="even">
<td style="text-align: left;">credit_history</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">existing_paid</td>
<td style="text-align: right;">530</td>
</tr>
<tr class="odd">
<td style="text-align: left;">purpose</td>
<td style="text-align: right;">10</td>
<td style="text-align: left;">radio_tv</td>
<td style="text-align: right;">280</td>
</tr>
<tr class="even">
<td style="text-align: left;">savings</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">less_100</td>
<td style="text-align: right;">603</td>
</tr>
<tr class="odd">
<td style="text-align: left;">employment</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">1_4</td>
<td style="text-align: right;">339</td>
</tr>
<tr class="even">
<td style="text-align: left;">personal_status_sex</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">male_single</td>
<td style="text-align: right;">548</td>
</tr>
<tr class="odd">
<td style="text-align: left;">other_debtors</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">none</td>
<td style="text-align: right;">907</td>
</tr>
<tr class="even">
<td style="text-align: left;">property</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">car_or_other</td>
<td style="text-align: right;">332</td>
</tr>
<tr class="odd">
<td style="text-align: left;">other_installment_plans</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">none</td>
<td style="text-align: right;">814</td>
</tr>
<tr class="even">
<td style="text-align: left;">housing</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">own</td>
<td style="text-align: right;">713</td>
</tr>
<tr class="odd">
<td style="text-align: left;">job</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">skilled_official</td>
<td style="text-align: right;">630</td>
</tr>
<tr class="even">
<td style="text-align: left;">telephone</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">none</td>
<td style="text-align: right;">596</td>
</tr>
<tr class="odd">
<td style="text-align: left;">foreign_worker</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">yes</td>
<td style="text-align: right;">963</td>
</tr>
<tr class="even">
<td style="text-align: left;">default</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">good</td>
<td style="text-align: right;">700</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Frecuencias de variables categóricas</caption>
<colgroup>
<col style="width: 29%">
<col style="width: 51%">
<col style="width: 4%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: left;">Categoria</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">Porcentaje</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">checking_status</td>
<td style="text-align: left;">0_200</td>
<td style="text-align: right;">269</td>
<td style="text-align: right;">26.9</td>
</tr>
<tr class="even">
<td style="text-align: left;">checking_status</td>
<td style="text-align: left;">greater_200</td>
<td style="text-align: right;">63</td>
<td style="text-align: right;">6.3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">checking_status</td>
<td style="text-align: left;">less_0</td>
<td style="text-align: right;">274</td>
<td style="text-align: right;">27.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">checking_status</td>
<td style="text-align: left;">no_account</td>
<td style="text-align: right;">394</td>
<td style="text-align: right;">39.4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">credit_history</td>
<td style="text-align: left;">all_paid</td>
<td style="text-align: right;">49</td>
<td style="text-align: right;">4.9</td>
</tr>
<tr class="even">
<td style="text-align: left;">credit_history</td>
<td style="text-align: left;">critical_other</td>
<td style="text-align: right;">293</td>
<td style="text-align: right;">29.3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">credit_history</td>
<td style="text-align: left;">delay</td>
<td style="text-align: right;">88</td>
<td style="text-align: right;">8.8</td>
</tr>
<tr class="even">
<td style="text-align: left;">credit_history</td>
<td style="text-align: left;">existing_paid</td>
<td style="text-align: right;">530</td>
<td style="text-align: right;">53.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">credit_history</td>
<td style="text-align: left;">no_credit_all_paid</td>
<td style="text-align: right;">40</td>
<td style="text-align: right;">4.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">default</td>
<td style="text-align: left;">bad</td>
<td style="text-align: right;">300</td>
<td style="text-align: right;">30.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">default</td>
<td style="text-align: left;">good</td>
<td style="text-align: right;">700</td>
<td style="text-align: right;">70.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">employment</td>
<td style="text-align: left;">1_4</td>
<td style="text-align: right;">339</td>
<td style="text-align: right;">33.9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">employment</td>
<td style="text-align: left;">4_7</td>
<td style="text-align: right;">174</td>
<td style="text-align: right;">17.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">employment</td>
<td style="text-align: left;">greater_7</td>
<td style="text-align: right;">253</td>
<td style="text-align: right;">25.3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">employment</td>
<td style="text-align: left;">less_1</td>
<td style="text-align: right;">172</td>
<td style="text-align: right;">17.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">employment</td>
<td style="text-align: left;">unemployed</td>
<td style="text-align: right;">62</td>
<td style="text-align: right;">6.2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">foreign_worker</td>
<td style="text-align: left;">yes</td>
<td style="text-align: right;">963</td>
<td style="text-align: right;">96.3</td>
</tr>
<tr class="even">
<td style="text-align: left;">foreign_worker</td>
<td style="text-align: left;">no</td>
<td style="text-align: right;">37</td>
<td style="text-align: right;">3.7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">housing</td>
<td style="text-align: left;">for_free</td>
<td style="text-align: right;">108</td>
<td style="text-align: right;">10.8</td>
</tr>
<tr class="even">
<td style="text-align: left;">housing</td>
<td style="text-align: left;">own</td>
<td style="text-align: right;">713</td>
<td style="text-align: right;">71.3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">housing</td>
<td style="text-align: left;">rent</td>
<td style="text-align: right;">179</td>
<td style="text-align: right;">17.9</td>
</tr>
<tr class="even">
<td style="text-align: left;">job</td>
<td style="text-align: left;">management_self_employed_highly_qualified</td>
<td style="text-align: right;">148</td>
<td style="text-align: right;">14.8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">job</td>
<td style="text-align: left;">skilled_official</td>
<td style="text-align: right;">630</td>
<td style="text-align: right;">63.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">job</td>
<td style="text-align: left;">unemployed_unskilled</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">2.2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">job</td>
<td style="text-align: left;">unskilled_resident</td>
<td style="text-align: right;">200</td>
<td style="text-align: right;">20.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">other_debtors</td>
<td style="text-align: left;">co_applicant</td>
<td style="text-align: right;">41</td>
<td style="text-align: right;">4.1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">other_debtors</td>
<td style="text-align: left;">guarantor</td>
<td style="text-align: right;">52</td>
<td style="text-align: right;">5.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">other_debtors</td>
<td style="text-align: left;">none</td>
<td style="text-align: right;">907</td>
<td style="text-align: right;">90.7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">other_installment_plans</td>
<td style="text-align: left;">none</td>
<td style="text-align: right;">814</td>
<td style="text-align: right;">81.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">other_installment_plans</td>
<td style="text-align: left;">bank</td>
<td style="text-align: right;">139</td>
<td style="text-align: right;">13.9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">other_installment_plans</td>
<td style="text-align: left;">stores</td>
<td style="text-align: right;">47</td>
<td style="text-align: right;">4.7</td>
</tr>
<tr class="even">
<td style="text-align: left;">personal_status_sex</td>
<td style="text-align: left;">female_divorced_separated_married</td>
<td style="text-align: right;">310</td>
<td style="text-align: right;">31.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">personal_status_sex</td>
<td style="text-align: left;">male_divorced_separated</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">5.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">personal_status_sex</td>
<td style="text-align: left;">male_married</td>
<td style="text-align: right;">92</td>
<td style="text-align: right;">9.2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">personal_status_sex</td>
<td style="text-align: left;">male_single</td>
<td style="text-align: right;">548</td>
<td style="text-align: right;">54.8</td>
</tr>
<tr class="even">
<td style="text-align: left;">property</td>
<td style="text-align: left;">building_society_savings_life_insurance</td>
<td style="text-align: right;">232</td>
<td style="text-align: right;">23.2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">property</td>
<td style="text-align: left;">car_or_other</td>
<td style="text-align: right;">332</td>
<td style="text-align: right;">33.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">property</td>
<td style="text-align: left;">real_estate</td>
<td style="text-align: right;">282</td>
<td style="text-align: right;">28.2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">property</td>
<td style="text-align: left;">unknown_no_property</td>
<td style="text-align: right;">154</td>
<td style="text-align: right;">15.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">purpose</td>
<td style="text-align: left;">business</td>
<td style="text-align: right;">97</td>
<td style="text-align: right;">9.7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">purpose</td>
<td style="text-align: left;">car_new</td>
<td style="text-align: right;">234</td>
<td style="text-align: right;">23.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">purpose</td>
<td style="text-align: left;">car_used</td>
<td style="text-align: right;">103</td>
<td style="text-align: right;">10.3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">purpose</td>
<td style="text-align: left;">domestic_appliances</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">1.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">purpose</td>
<td style="text-align: left;">education</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">5.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">purpose</td>
<td style="text-align: left;">furniture_equipment</td>
<td style="text-align: right;">181</td>
<td style="text-align: right;">18.1</td>
</tr>
<tr class="even">
<td style="text-align: left;">purpose</td>
<td style="text-align: left;">others</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">1.2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">purpose</td>
<td style="text-align: left;">radio_tv</td>
<td style="text-align: right;">280</td>
<td style="text-align: right;">28.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">purpose</td>
<td style="text-align: left;">repairs</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">2.2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">purpose</td>
<td style="text-align: left;">retraining</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">0.9</td>
</tr>
<tr class="even">
<td style="text-align: left;">savings</td>
<td style="text-align: left;">100_500</td>
<td style="text-align: right;">103</td>
<td style="text-align: right;">10.3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">savings</td>
<td style="text-align: left;">500_1000</td>
<td style="text-align: right;">63</td>
<td style="text-align: right;">6.3</td>
</tr>
<tr class="even">
<td style="text-align: left;">savings</td>
<td style="text-align: left;">greater_1000</td>
<td style="text-align: right;">48</td>
<td style="text-align: right;">4.8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">savings</td>
<td style="text-align: left;">less_100</td>
<td style="text-align: right;">603</td>
<td style="text-align: right;">60.3</td>
</tr>
<tr class="even">
<td style="text-align: left;">savings</td>
<td style="text-align: left;">unknown</td>
<td style="text-align: right;">183</td>
<td style="text-align: right;">18.3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">telephone</td>
<td style="text-align: left;">none</td>
<td style="text-align: right;">596</td>
<td style="text-align: right;">59.6</td>
</tr>
<tr class="even">
<td style="text-align: left;">telephone</td>
<td style="text-align: left;">yes</td>
<td style="text-align: right;">404</td>
<td style="text-align: right;">40.4</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>A continuación se presentan las gráficas de barras para las variables categóricas asociadas a aspectos financieros del crédito:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="taller3_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Igualmente, se grafican las variables socioeconómicas de los solicitantes, lo cual también contribuye a la construcción de un perfil de riesgo:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="taller3_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Finalmente se establecen las características asociadas al entorno laboral como una característica relevante del individuo ya que permitiría ser un medio de solvencia para respaldar al crédito:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="taller3_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>El análisis de frecuencias permitió caracterizar el perfil general de los solicitantes de crédito incluidos en la base de datos <em>German Credit</em>. En relación con el estado de la cuenta corriente (<em>checking_status</em>), se observó que el 39,4% de los clientes no posee cuenta corriente, mientras que el 27,4% presenta saldos inferiores a cero y el 26,9% mantiene saldos entre 0 y 200 DM. Solamente el 6,3% dispone de saldos superiores a 200 DM, lo que sugiere que una proporción importante de los solicitantes presenta una capacidad financiera limitada.</p>
<p>Respecto al historial crediticio (<em>credit_history</em>), la categoría predominante corresponde a clientes con créditos pagados oportunamente hasta el momento (<em>existing_paid</em>), representando el 53,0% de las observaciones. Asimismo, el 29,3% pertenece a la categoría de cuentas críticas u otros créditos existentes (<em>critical/other</em>), mientras que únicamente el 8,8% registra antecedentes de retrasos en pagos.</p>
<p>En cuanto al propósito del crédito (<em>purpose</em>), los destinos más frecuentes fueron la adquisición de radio o televisión (28,0%), vehículos nuevos (23,4%) y muebles o equipamiento para el hogar (18,1%). Estos resultados indican que la mayoría de los créditos está orientada al financiamiento de bienes de consumo duradero.</p>
<p>La variable de ahorro (<em>savings</em>) evidenció que el 60,3% de los solicitantes posee menos de 100 DM en ahorros, mientras que apenas el 4,8% cuenta con más de 1.000 DM. Este comportamiento sugiere una limitada capacidad de respaldo financiero para una proporción considerable de los clientes.</p>
<p>En relación con la estabilidad laboral (<em>employment</em>), el 33,9% de los individuos registra entre uno y cuatro años de antigüedad laboral y el 25,3% acumula más de siete años de experiencia en su empleo actual. Por otra parte, solamente el 6,2% se encuentra desempleado.</p>
<p>El análisis de las demás variables revela que la mayoría de los solicitantes son hombres solteros (<em>male_single</em>, 54,8%), no cuentan con otros deudores o garantes (<em>other_debtors</em>, 90,7%), poseen vivienda propia (<em>housing</em>, 71,3%) y desempeñan ocupaciones calificadas o cargos oficiales (<em>job</em>, 63,0%). Adicionalmente, el 96,3% corresponde a trabajadores extranjeros según la codificación original del conjunto de datos.</p>
</section>
<section id="análisis-bivariado-y-relación-con-variable-target" class="level3">
<h3 class="anchored" data-anchor-id="análisis-bivariado-y-relación-con-variable-target">Análisis bivariado y relación con variable target</h3>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="taller3_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Las variables financieras presentan una relación importante con la variable objetivo (<em>default</em>). El <strong>estado de la cuenta corriente (checking_status)</strong> es uno de los factores más discriminantes: los clientes sin cuenta corriente (<em>no_account</em>) registran aproximadamente un <strong>88% de buenos pagadores</strong>, mientras que aquellos con saldos negativos (<em>less_0</em>) presentan una distribución cercana al <strong>50% de buenos y 50% de malos pagadores</strong>, evidenciando un mayor riesgo crediticio. De manera similar, la variable <strong>ahorros (savings)</strong> muestra que los clientes con mayores niveles de ahorro (<em>greater_1000</em> y <em>500_1000</em>) alcanzan porcentajes de buen comportamiento superiores al 80%, mientras que quienes poseen menos de 100 unidades monetarias presentan una proporción significativamente mayor de incumplimiento. Respecto al <strong>historial crediticio</strong>, las categorías <em>critical_other</em> y <em>existing_paid</em> muestran desempeños favorables, mientras que los clientes con antecedentes de créditos totalmente pagados o sin historial previo (<em>all_paid</em> y <em>no_credit_all_paid</em>) registran mayores porcentajes de incumplimiento. Finalmente, algunos propósitos del crédito como <em>car_used</em>, <em>radio_tv</em> y <em>retraining</em> exhiben menores niveles de riesgo, mientras que categorías como <em>education</em>, <em>others</em> y <em>car_new</em> presentan proporciones relativamente más altas de clientes clasificados como <em>bad</em>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="taller3_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Las variables sociodemográficas muestran diferencias moderadas en la distribución del riesgo crediticio. En cuanto al <strong>tipo de vivienda (housing)</strong>, los clientes con vivienda propia presentan aproximadamente un <strong>74% de buenos pagadores</strong>, superando a quienes viven en arriendo o disponen de vivienda gratuita, donde el porcentaje de incumplimiento es mayor. Respecto al <strong>estado civil y sexo (personal_status_sex)</strong>, las diferencias observadas son relativamente pequeñas, aunque los hombres casados y solteros muestran una proporción ligeramente superior de clientes con buen comportamiento crediticio en comparación con otros grupos. Por otra parte, la variable <strong>tipo de propiedad (property)</strong> evidencia una asociación más marcada con el riesgo: los clientes propietarios de bienes raíces (<em>real_estate</em>) presentan cerca de un <strong>78% de buenos pagadores</strong>, mientras que aquellos clasificados como <em>unknown_no_property</em> registran el mayor porcentaje de incumplimiento (44%). Estos resultados sugieren que la posesión de activos constituye una señal positiva de solvencia financiera.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="taller3_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Las características laborales también presentan patrones asociados al comportamiento crediticio. La <strong>antigüedad laboral (employment)</strong> muestra una relación positiva con el cumplimiento de las obligaciones financieras, ya que los clientes con entre cuatro y siete años de permanencia laboral alcanzan aproximadamente un <strong>78% de buenos pagadores</strong>, mientras que quienes tienen menos de un año de experiencia laboral presentan los niveles más altos de incumplimiento. En cuanto a la <strong>ocupación (job)</strong>, las diferencias son menos pronunciadas, aunque los trabajadores calificados y residentes permanentes presentan porcentajes ligeramente superiores de buen comportamiento crediticio. La variable <strong>teléfono (telephone)</strong> no evidencia diferencias relevantes entre categorías, lo que sugiere un bajo poder explicativo sobre el riesgo. Finalmente, aunque la variable <strong>foreign_worker</strong> muestra una diferencia considerable entre categorías, debe interpretarse con cautela debido al fuerte desbalance de la muestra, ya que más del 96% de los registros corresponden a trabajadores extranjeros. En conjunto, estos resultados indican que la estabilidad laboral parece ser un factor más relevante para explicar el comportamiento crediticio que la ocupación específica o la disponibilidad de teléfono.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="taller3_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Los diagramas de violín permiten comparar la distribución de las variables numéricas entre los clientes clasificados como <em>good</em> y <em>bad</em>. Se observa que las diferencias más marcadas se presentan en las variables <strong>duration</strong> y <strong>credit_amount</strong>, donde los clientes con comportamiento crediticio desfavorable (<em>bad</em>) tienden a solicitar créditos de mayor duración y montos más elevados en comparación con los clientes clasificados como <em>good</em>. Este comportamiento sugiere que créditos más largos y de mayor cuantía podrían estar asociados con un mayor riesgo de incumplimiento. Por otra parte, variables como <strong>age</strong>, <strong>existing_credits</strong>, <strong>people_liable</strong> y <strong>residence_since</strong> muestran distribuciones muy similares entre ambos grupos, evidenciando un poder discriminatorio limitado. La variable <strong>installment_rate</strong> tampoco presenta diferencias sustanciales, aunque se aprecia una ligera concentración de clientes con incumplimiento en las categorías más altas de la tasa de cuota. En conjunto, los resultados indican que la duración y el monto del crédito son las variables numéricas con mayor capacidad para diferenciar entre buenos y malos pagadores.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="taller3_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
<p>La matriz de dispersión permite evaluar simultáneamente la relación entre las variables numéricas y la separación entre las clases de la variable objetivo. En términos generales, se observa un amplio solapamiento entre los clientes <em>good</em> y <em>bad</em>, lo que indica que ninguna variable individual es suficiente para discriminar completamente el comportamiento crediticio. No obstante, se identifica una relación positiva moderada entre <strong>duration</strong> y <strong>credit_amount</strong>, donde créditos de mayor monto suelen estar asociados con plazos más extensos. Asimismo, los clientes con incumplimiento tienden a concentrarse con mayor frecuencia en las zonas correspondientes a montos y duraciones elevadas, reforzando los hallazgos observados en los diagramas de violín. Las demás variables presentan relaciones débiles o prácticamente inexistentes entre sí, y las distribuciones de ambas clases son muy similares. Estos resultados sugieren que la capacidad predictiva del modelo probablemente dependerá de la combinación simultánea de múltiples variables más que de una sola característica aislada.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="taller3_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>La matriz de correlación evidencia que, en general, las variables numéricas del conjunto de datos presentan relaciones lineales débiles o moderadas, lo que sugiere una baja presencia de multicolinealidad. La asociación más fuerte se observa entre <strong>duration</strong> y <strong>credit_amount</strong> (<em>r = 0.62</em>), indicando que los créditos de mayor monto tienden a otorgarse con plazos más largos. Esta relación es consistente con la lógica financiera, ya que montos elevados suelen requerir períodos de amortización más extensos para mantener cuotas manejables para el cliente.</p>
<p>Por otra parte, se identifica una correlación negativa moderada entre <strong>credit_amount</strong> e <strong>installment_rate</strong> (<em>r = -0.27</em>), lo que sugiere que los créditos de mayor cuantía tienden a estar asociados con tasas de cuota relativamente menores respecto al ingreso disponible. Asimismo, la variable <strong>residence_since</strong> presenta una correlación positiva moderada con <strong>age</strong> (<em>r = 0.27</em>), indicando que las personas de mayor edad tienden a acumular más tiempo de residencia en su vivienda actual.</p>
<p>Las demás correlaciones son bajas, con coeficientes inferiores a 0.20 en valor absoluto. Entre ellas destacan las asociaciones positivas entre <strong>age</strong> y <strong>existing_credits</strong> (<em>r = 0.15</em>), <strong>age</strong> y <strong>people_liable</strong> (<em>r = 0.12</em>), así como entre <strong>existing_credits</strong> y <strong>people_liable</strong> (<em>r = 0.11</em>). Aunque estas relaciones son estadísticamente apreciables, su magnitud es reducida y no sugiere una dependencia fuerte entre las variables.</p>
<p>En términos generales, los resultados indican que las variables numéricas aportan información complementaria y relativamente independiente al análisis del riesgo crediticio. La ausencia de correlaciones elevadas (superiores a 0.80) constituye un resultado favorable para etapas posteriores de modelado, ya que reduce el riesgo de problemas asociados a la multicolinealidad y permite que cada variable contribuya con información propia al proceso de clasificación del comportamiento crediticio.</p>
</section>
</section>
<section id="preprocesamiento-de-datos" class="level2">
<h2 class="anchored" data-anchor-id="preprocesamiento-de-datos">Preprocesamiento de datos</h2>
<p>Con base en el análisis exploratorio, se presenta una alta cardinalidad en las variable purpose. Para este caso, se agruparán sus categorías por su naturaleza de la siguiente manera:</p>
<ul>
<li><p>Vehículos: <code>car_new, car_used</code></p></li>
<li><p>Hogar: <code>radio_tv, furniture_equipment, domestic_appliances, repairs</code></p></li>
<li><p>Inversión/Desarrollo: <code>business, education, retraining</code></p></li>
<li><p>Otros: <code>others</code></p></li>
</ul>
<p>A continuación, se presenta las agrupaciones y sus respectivos resultados:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="taller3_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="taller3_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>